name: Deploy to IPFS

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Deploy to IPFS
        uses: ipfs/ipfs-deploy-action@v1
        id: deploy
        with:
          path-to-deploy: dist
          kubo-api-url: ${{ secrets.KUBO_API_URL }}
          kubo-api-auth	: ${{ secrets.KUBO_API_AUTH }}
          github-token: ${{ github.token }}

      - name: Publish to IPNS
        run: |
          OUTPUT=$(ipfs --api=${{ secrets.KUBO_API_URL }} --api-auth=${{ secrets.KUBO_API_AUTH }} name publish --key=self ${{ steps.deploy.outputs.cid }})
          echo "$OUTPUT"
          echo "✅ $OUTPUT" >> $GITHUB_STEP_SUMMARY
